### ISSUE TITLE
`meta-add` example issue

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#103]
I created myself a metadata set with `meta-extract` and then played with `meta-add`. Here is a protocol:

```sh
% dl -C meta1 meta-extract metalad_core_dataset | tee meta.json | jq
{
  "type": "dataset",
  "dataset_id": "ab24f1ea-72ad-48c2-bb83-4fdefb39c341",
  "dataset_version": "6b6849649536af653e4044d1a590de05fdc44a47",
  "extractor_name": "metalad_core_dataset",
  "extractor_version": "0.0.1",
  "extraction_parameter": {},
  "extraction_time": 1618295626.0780263,
  "agent_name": "Michael Hanke",
  "agent_email": "michael.hanke@gmail.com",
  "extracted_metadata": {
    "id": "ab24f1ea-72ad-48c2-bb83-4fdefb39c341",
    "refcommit": "6b6849649536af653e4044d1a590de05fdc44a47",
    "inter_dataset_path": "",
    "comment": "test-implementation of core_dataset"
  }
}
```

Following the example "Add metadata stored in the file "metadata-123.json" to the metadata
model instance in the current directory."

```
% datalad meta-add meta.json
[ERROR  ] 'dict' object has no attribute 'to_json_obj' [metadata.py:to_json_obj:96] (AttributeError) 
```

I assume that this is not meant to work (my PWD has no Git repo), but a user that starts from the docs might have a hard time making that connection -- they suggest any directory is fine.

However, inside a dataset also doesn't work:

```
% git log -1 --pretty=oneline | cat
a24a798a2a1d261d783fb8b808ce62d125cc05f5 [DATALAD] new dataset
% dl meta-add ../meta.json
[ERROR  ] 'dict' object has no attribute 'to_json_obj' [metadata.py:to_json_obj:96] (AttributeError) 
```

So possibly this is not about where I execute and which store is used, but about the content of the metadata record. I suspect that it may need additional keys described in the docs:

> It may in addition contain either all or none of the following keys (they are used to add metadata element as a sub-dataset element, i.e. perform aggregation): 'root_dataset_id' 'root_dataset_version', 'inter_dataset_path'.

However, those are described as optional and the examples do not cover my use case (stored output of `meta-extract`).

**Comment by christian-monch** [comment]
I think the 'dict' object has no attribute 'to_json_obj'-error stems from a mismatch in the versions of the metadata-model and the metalad. "pip install -r requirements-devel.txt" should fix this.

Currently the error diagnosis message that is displayed when datalad meta-add is instructed to add metadata to a git repository in the current directory, i.e. `datalad meta-add meta.json`, looks something like this:

```
RuntimeError: Command failed (exit code: 128) git -P --git-dir ./.git hash-object -w --stdin:
STDOUT:
STDERR:
fatal: No Git-Repository: './.git'
```

Additional keys are not necessary if the metadata should just be associated with a root dataset in the metadata store. Example with the latest version:

```
> datalad meta-extract metalad_core_dataset|tee meta.json|jq
{
  "type": "dataset",
  "dataset_id": "95494b0f-d6b3-4d85-9fa4-588d33cc84a2",
  "dataset_version": "5b1459f80b26f90eb805cf0f6295260e43cc9f43",
  "extractor_name": "metalad_core_dataset",
  "extractor_version": "0.0.1",
  "extraction_parameter": {},
  "extraction_time": 1618325712.0097125,
  "agent_name": "Christian Mönch",
  "agent_email": "christian.moench@web.de",
  "extracted_metadata": {
    "id": "95494b0f-d6b3-4d85-9fa4-588d33cc84a2",
    "refcommit": "5b1459f80b26f90eb805cf0f6295260e43cc9f43",
    "dataset_path": "",
    "comment": "test-implementation of core_dataset"
  }
}

> datalad meta-add meta.json 
add(ok): (dataset) [added dataset metadata]

> datalad meta-dump -r |jq
{
  "type": "dataset",
  "dataset_id": "95494b0f-d6b3-4d85-9fa4-588d33cc84a2",
  "dataset_version": "5b1459f80b26f90eb805cf0f6295260e43cc9f43",
  "extractor_name": "metalad_core_dataset",
  "extractor_version": "0.0.1",
  "extraction_parameter": {},
  "extraction_time": 1618325712.0097125,
  "agent_name": "Christian Mönch",
  "agent_email": "christian.moench@web.de",
  "extracted_metadata": {
    "id": "95494b0f-d6b3-4d85-9fa4-588d33cc84a2",
    "refcommit": "5b1459f80b26f90eb805cf0f6295260e43cc9f43",
    "dataset_path": "",
    "comment": "test-implementation of core_dataset"
  }
}
```

The subtree under which the metadata is stored is empty, i.e. "". Therefore it is not shown in the dump-ed metadata record. Otherwise the record would contain the key "dataset_path" (formerly: "inter_dataset_path").


The additional keys are used to "associate" the record with a sub-dataset that is contained within the super dataset in a given path. For example:

Assume we have a super dataset located in "/home/super_dataset". This dataset has a sub dataset called "project_1" located at "/home/super_dataset/projects/project_1". We can extract metadata in the sub dataset:

```
> cd /home/super_dataset/projects/project_1
> datalad meta-extract metalad_core_dataset|tee meta.json|jq
{
  "type": "dataset",
  "dataset_id": "edf3c027-afa0-4b34-8903-dab4b90ce264",
  "dataset_version": "98a8825754b56d398df02eeffcc93fc2457aaeda",
  "extractor_name": "metalad_core_dataset",
  "extractor_version": "0.0.1",
  "extraction_parameter": {},
  "extraction_time": 1618326860.658123,
  "agent_name": "Christian Mönch",
  "agent_email": "christian.moench@web.de",
  "extracted_metadata": {
    "id": "edf3c027-afa0-4b34-8903-dab4b90ce264",
    "refcommit": "98a8825754b56d398df02eeffcc93fc2457aaeda",
    "dataset_path": "",
    "comment": "test-implementation of core_dataset"
  }
}
```
The we use meta-add to add the extracted metadata to the metadata store of the super-dataset, by adding the super dataset id, the super dataset version and the relative path of the sub dataset as additional values.

```
> cd /home/super_dataset/projects/project_1
> datalad meta-add -m ../../ meta.json '{"root_dataset_id": "4ab5213a-c332-4a5d-afcc-0a601c32c007", "root_dataset_version": "bfccfef2f0c38b60f286ea68755903f68ca4c982", "dataset_path": "projects/project_1"}'
add(ok): (dataset) [added dataset metadata]
```

When we dump the super datasets metadata, we see the sub dataset entry in it (it is the only entry, since we did not yet add the super dataset), this time is has the key "dataset_path":

```
> datalad meta-dump -m ../../ -r|jq
{
  "type": "dataset",
  "dataset_id": "edf3c027-afa0-4b34-8903-dab4b90ce264",
  "dataset_version": "98a8825754b56d398df02eeffcc93fc2457aaeda",
  "root_dataset_id": "4ab5213a-c332-4a5d-afcc-0a601c32c007",
  "root_dataset_version": "bfccfef2f0c38b60f286ea68755903f68ca4c982",
  "dataset_path": "projects/project_1",
  "extractor_name": "metalad_core_dataset",
  "extractor_version": "0.0.1",
  "extraction_parameter": {},
  "extraction_time": 1618326860.658123,
  "agent_name": "Christian Mönch",
  "agent_email": "christian.moench@web.de",
  "extracted_metadata": {
    "id": "edf3c027-afa0-4b34-8903-dab4b90ce264",
    "refcommit": "98a8825754b56d398df02eeffcc93fc2457aaeda",
    "dataset_path": "",
    "comment": "test-implementation of core_dataset"
  }
}
```

**Comment by christian-monch** [comment]
The complete chain was verified with version a5f542cd5c88166feb0e18f1b5515554260d26a0 of datalad-metalad. You might have to ensure that the requirements are re-installed

**Comment by christian-monch** [comment]
Another potential source of problems is an old version of metadata in a metadata store. In order to facilitate generic metadata content, the MetadataInstance class was modified. That also changed its serialization, and old metadata cannot be read anymore. A new commit in metadata-model, i.e. b2d7b4265537932db2f81bad6bd6ea953c10241a,  will check for this condition and report an error.

**Comment by christian-monch** [comment]
PR #112 should fix all of the above issues
