### ISSUE TITLE
ENH: update legacy extractors to derive from more recent `MetadataExtractorBase` class

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-metalad#316]

**Comment by christian-monch** [comment]
In order to do this I see two possibilities:

1. Rewrite the legacy extractors to fit the new interface and processing paradigm
2. Write an adaptor-layer that translates the new interface into calls to the old interface

Possibilitiy 1. would be quite some work, and we would not cover external extractors, which we still should support. Possibility 2. is what is more or less implemented in ``meta-add``, a layer that translates the dataset-level / file-level paradigm to the old list of statuses-paradigm.

There might still be a good reason to rewrite specific extractors, for example, to improve performance. To assess any improvements we should do a test on one extractor, e.g. ``metalad_core``. I added an issue for this here: https://github.com/datalad/datalad-metalad/issues/320

I will close this issue because it is too general.
