### ISSUE TITLE
meta-dump: result-record structure

### ISSUE THREAD

**Issue by mih** [datalad/datalad-metalad#84]
Demo:

```
% datalad -f json_pp meta-dump '.:*'
{
  "action": "meta_dump",
  "metadata": {
    "file_level_metadata": {
      "dataset_path": "",
      "file_path": "mike",
      "metadata": {
        "metalad_core_file": [
          {
            "extraction_agent": "Michael Hanke <michael.hanke@gmail.com>",
            "extraction_time": 1616420513.731246,
            "extractor_parameter": {},
            "extractor_result": {
              "@": {
                "type": "ImmediateMetadataSource",
                "version": "1.0"
              },
              "content": {
                "@id": "datalad:SHA1-s4--a8fdc205a9f19cc1c7507a60c4f01b13d11d7fd0",
                "comment": "test-implementation",
                "content_byte_size": 108,
                "intra_dataset_path": "mike",
                "path": "/tmp/mike/mike",
                "type": "file"
              },
              "metadata_source_type": "ImmediateMetadataSource"
            },
            "extractor_version": "0.0.1"
          }
        ]
      },
      "root_dataset_identifier": "b31eab6e-ca6b-4b8f-b6d5-55bdfeb89b75",
      "root_dataset_version": "6317916a0c986155041cf114e4e5cff0c9c4850e"
    }
  },
  "source": {
    "mapper": "git",
    "realm": "."
  },
  "status": "ok",
  "type": "file"
}
```

Given that these result records, and their structure are essential for interoperability with other datalad pieces, we should discuss whether generic top-level property names like `metadata` or `source` are a good fit.

For me, the scope of `meta-dump` is to be used in scripts (to pass a dump on to some other parser). While we have no control over the structure of metadata returned by an extractor, we should make generic meta information, such as dataset component types and locations, maximally easy to access.

Concretely, I'd say:

- `.metadata.file_level_metadata.metadata` should move up to become `.metadata`
- `.metadata.file_level_metadata.file_path` should become `.path`
- `.metadata.file_level_metadata.(file|dataset)_path` should be evaluated to become `.type=file|dataset`

**Comment by christian-monch** [comment]
While separating metadata extraction and metadata insertion (issue #93), I thought about using individual records for the smallest metadata elements, i.e. metadata extracted by an extractor on a given dataset or file with a specific set of parameters. Those records can then be emitted by meta-extract and can be used by meta-add to add them into a metadata store.

Example:

```json
{
    "extractor_name": "metalad_core_file",
    "extractor_version": "1.0",
    "extraction_parameter": {"p1": "v1"},
    "extraction_time": 111155555.6666,
    "agent_name": "Michael Hanke",
    "agent_email": "<michael.hanke@gmail.com>",
    "dataset_id": "b31eab6e-ca6b-4b8f-b6d5-55bdfeb89b75",
    "dataset_version": "",
    "metadata_type": "file",
    "file_path": "mike/mike/some_content.yaml",

    "extracted_metadata": {
        "@id": "datalad:SHA1-s4--a8fdc205a9f19cc1c7507a60c4f01b13d11d7fd0",
        "comment": "test-implementation",
        "content_byte_size": 108,
        "intra_dataset_path": "mike",
        "path": "mike/mike/some_content.yaml",
        "type": "file"
    }
}
```

This record is self-contained since it carries enough information to add it to a metadata model instance (which in turn is mapped onto a git-backend). (The property "file_path" would only be present if the property "metadata_type" equals "file". If the metadata property equals "dataset", the "file_path" property must not be present.)

The extracted metadata itself is contained in the property "extracted_metadata". It is treated as an opaque JSON structure. meaning, we assume it is a JSON structure and can be serialized when it is added to the metadata model instance, but we do not interpret it. It is just passed through.

In principle this would allow for something like:  `meta-extract ... | meta-add ...` (and if we use the same record structure for meta-dump, something like `meta-dump ...|meta-add ...` would alsow work). The record can be extended by the following three properties, to add it to the metadata of a sub-dataset:

```json
    "root_dataset_id": "b31eab6e-ca6b-4b8f-b6d5-55bdfeb89b75",
    "root_dataset_version": "6317916a0c986155041cf114e4e5cff0c9c4850e",
    "dataset_path": "subdataset_1",
```

The meta-add command allows to override or add properties to a given record on the command line. With something like `meta-dump | meta-add ....  '{"root_dataset_id": ....}'`, one could even perform aggregation outside of meta-aggregate. Not that you would like to do that, but I think it is a good indicator of the versatility of the self-contained record approach.

For completeness a record that is added to a sub-dataset, by using the additional three properties `root_dataset_id`, `root_dataset_version`, and `inter_dataset_path` might look like this:

```json
{
    "extractor_name": "metalad_core_file",
    "extractor_version": "1.0",
    "extraction_parameter": {"p1": "v1"},
    "extraction_time": 111155555.6666,
    "agent_name": "Michael Hanke",
    "agent_email": "<michael.hanke@gmail.com>",
    "dataset_id": "b31eab6e-ca6b-4b8f-b6d5-55bdfeb89b75",
    "dataset_version": "",
    "metadata_type": "file",
    "path": "mike/mike/some_content.yam",

    "root_dataset_id": "b31eab6e-ca6b-4b8f-b6d5-55bdfeb89b75",
    "root_dataset_version": "6317916a0c986155041cf114e4e5cff0c9c4850e",
    "inter_dataset_path": "subdataset_1",

    "extracted_metadata": {
        "@id": "datalad:SHA1-s4--a8fdc205a9f19cc1c7507a60c4f01b13d11d7fd0",
        "comment": "test-implementation",
        "content_byte_size": 108,
        "intra_dataset_path": "mike",
        "path": "mike/mike/some_content.yam",
        "type": "file"
    }
}
```


The record

**Comment by christian-monch** [comment]
Output of `meta-dump` & `meta-extract` and input for `meta-add` is structured as described above.

**Comment by christian-monch** [comment]
Revisit the result structure. Absolute "path"-key is either missing or has a relative path in some metalad commands, e.g. meta-extract

**Comment by christian-monch** [comment]
Addresses in PR #122
